library(caret)
library(dplyr)
library(KNN)

df_imputed <- read.csv('full_set.csv')

set.seed(123)
df_imputed <- df_imputed[, !names(df_imputed) %in% c('X', 'X.1')]
df_imputed$year <- as.factor(df_imputed$year)

#decision tree
cv = trainControl(method = 'cv', n = 10)
tree_mod <- train(Market.Cap~., df_imputed, method = 'rpart', trControl = cv)
saveRDS(tree_mod, 'tree_mod.rds')

tree_imp1 <- varImp(tree_mod)
plot(tree_imp, top = 10)


#Stock.based.compensation         100.00
#Income.Tax.Expense                65.84
#Consolidated.Income               62.75
#Dividend.payments                 52.68
#Operating.Cash.Flow               37.02
#R.D.Expenses                      35.22

tree_imp2 <- data.frame(tree_mod$finalModel$variable.importance)
par(mar=c(5,9,4,1)+.1)
barplot(tree_imp2$tree_mod.finalModel.variable.importance[10:1], horiz = TRUE, las = 1, names.arg = rownames(tree_imp2)[10:1], col = 4, cex.names = 0.8, cex.axis = 0.8, main = 'List of Variables by Importance')

#Consolidated.Income                                    1.015179e+25
#Dividend.payments                                      3.894715e+24
#Stock.based.compensation                               3.792306e+24
#Income.Tax.Expense                                     3.432909e+24
#Retained.earnings..deficit.                            3.420713e+24
#Operating.Cash.Flow                                    2.979331e+24
#Operating.Expenses                                     2.262084e+24
#R.D.Expenses                                           1.961538e+24
#Total.debt                                             9.153842e+23
#Long.term.debt                                         7.846150e+23
 
# Definitions
# Consolidated income: income that combines revenue, expenses, and income of parent company and subsidiaries - whole income rather than parts
# Dividend payments: distribution of a portion of company profit to payers
# Stock based compensation: how employees are rewarded in lieu of cash 
# Income tax expense: total amount of tax owed by corporation
# Retained earnings deficit: essentially debt - when company debts are greater than its profits
# Operating cash flow: Operating cash flow (OCF) is a measure of the amount of cash generated by a company's normal business operations. 
# Operating expenses: An operating expense is an expense a business incurs through its normal business operations. Often abbreviated as OPEX, operating expenses include rent, equipment, inventory costs, marketing, payroll, insurance, step costs, and funds allocated for research and development. 
# RD Expenses:  R&D expense (short for research and development expense) is essentially the amount of money that a company spends to develop new products and services each year.
# Total debt: Total debt is calculated by adding up a company's liabilities, or debts, which are categorized as short and long-term debt. 
# Long term debt: Long-term debt is debt that matures in more than one year and is often treated differently from short-term debt.
# long term debt and total debt are related

# Try linear regression
library(rcompanion)
lm <- train(Market.Cap~., df_new, method = 'glm', trControl = cv)
barplot(lm$finalModel$coefficients)
vif(lm$finalModel)
summary(lm$finalModel)
accuracy(lm)
sqrt(mean(lm$finalModel$residuals^2))


#from coefficients, we see that long term debt is significant while total debt is not
lm2 <- train(Market.Cap~., df_new[,!names(df_new) %in% c('Total.debt')], method = 'glm', trControl = cv)
summary(lm2$finalModel)
vif(lm2$finalModel)
accuracy(lm2)
sqrt(mean(lm2$finalModel$residuals^2))
# removing total debt didn't make a huge difference

# Try RF model
new_predictors <- rownames(tree_imp2)
df_new <- df_imputed[, new_predictors]
df_new$Market.Cap <- df_imputed$Market.Cap
rf <- train(Market.Cap~., df_new, method = 'rf', trControl = cv)
rf_importance <- sort(rf$finalModel$importance)
barplot(rf_importance, col = 4, horiz=TRUE, las=2, cex.names = 0.7)
rf
rf_importance
saveRDS(rf, 'rf.rds')



# Try unsupervised model KNN
